version: 2

sources:
  - name: tmdb
    schema: tmdb_analytics
    database: tmdb-analytics-prod
    tables:
      - name: movies
        description: >
          Raw movie data from TMDB API in Parquet format. Includes all credits for each movie.
          Source: TMDB API v3 https://api.themoviedb.org/3/movie/{movie_id} with append_to_response = "credits"

      
